baseURL = "/"
languageCode = "en-us"
title = "Roof Company"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"

[Author]
    name = "MB"
    email = "webdev@webdev-mb.pl"

[Social]
    twitter = "/"
